CREATE TABLE CLIENTI 
( id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nickname VARCHAR(128),
password VARCHAR(128),
acquisti INTEGER,
soldi INTEGER);

CREATE TABLE VENDITORI 
( id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nickname VARCHAR(128),
password VARCHAR(128),
venduti INTEGER,
soldi INTEGER);

INSERT INTO CLIENTI (id, nickname, password, acquisti, soldi)
VALUES (default, 'Peach', '111', 5, 102),
 (default, 'Wario', '222', 4, 74),
 (default, 'Bowser', '333', 3, 5004),
 (default, 'Luigi', '444', 15, 36),
 (default, 'Toad', '555', 1, 91);

INSERT INTO VENDITORI (id, nickname, password, venduti, soldi)
VALUES (default, 'Alessio', 'aaa', 5, 10),
 (default, 'Andrea', 'nnn', 7, 15),
 (default, 'Davide', 'ddd', 8, 155),
 (default, 'Matteo', 'mmm', 19, 1578),
 (default, 'Emanuel', 'eee', 1, 22),
 (default, 'Corrado', 'ccc', 5, 358);